name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/terumbu_karang.png
    - assets/Ikan-Glofish.jpg
    - assets/takari.jpg
    - assets/R.jpg
    - assets/ikan-cupang.jpg
    - assets/OIP.jpg
    - assets/OIP (1).jpg
    - assets/Banner Family Aqua.png
    - assets/Discus-Fish_.jpg
    - assets/ikan mas.jpg
    - assets/pompa air.jpeg
    - assets/lampu.jpg
    - assets/arwana.jpg
    - assets/mas.jpeg
    - assets/ikan.jpeg
